### ISSUE TITLE
Missing Days

### ISSUE THREAD

**Issue by Arindrew** [jayboo86/StickGame#1]
testing.py is missing the option to choose Friday or Saturday from its dayReturn function.

**Comment by jayboo86** [comment]
I halted doing the days of the week in the dayReturn function because I wanted to pivot to each day being its own function.

**Comment by jayboo86** [comment]
Not really sure how I want to go about it yet. lol  Also, I need to add in error handling for misspells but also account for Sunday vs sunday when answered.,
